defaults: &defaults 
  docker:
  - image: circleci/node:8.11.2
  - image: circleci/mongo:3.6.5-ram
    command: [mongod, --smallfiles]
  working_directory: ~/repo
version: 2
jobs:
  build-job:
    <<: *defaults  
    steps:
      - checkout
      - run: 
          name: update-npm
          command: 'sudo npm install -g npm@latest'
      # Download and cache dependencies
      - restore_cache:
          keys:
          - v1-dependencies-{{ checksum "package.json" }}
          # fallback to using the latest cache if no exact match is found
          - v1-dependencies-

      - run: 
          name: install-npm-wee
          command: npm install

      - save_cache:
          paths:
            - node_modules
          key: v1-dependencies-{{ checksum "package.json" }}

      - persist_to_workspace:
          root: ./
          paths: 
            - ./
  test-job:
    <<: *defaults
    environment:
      - NODE_ENV: "test"
    steps:
      - run:
          name: 'create build folder'
          command: 'mkdir build'
      - attach_workspace:
          at: ~/repo/build
    # run tests!
      - run: 
          name: test
          command: |
            cd build
            npm test
  increment-build-job:
    <<: *defaults
    steps:
      - run:
          name: 'create build folder'
          command: 'mkdir build'
      - attach_workspace:
          at: ~/repo/build
      - run:
          name: 'install jq'
          command: 'sudo apt-get install jq'
      - run:
          name: 'update build #'    
          command: |
            if [ $CIRCLE_BRANCH == "master" ]; then
              cd build
              node node_modules/appversion/apv update build
              TAG="$(jq '[.version.major , .version.minor, .version.patch, .build.number | tostring] | join (".")' appversion.json)"
              git tag -a $TAG -m 'build tag auto-updated'
              git add .
              git commit -m "${TAG}"
              git push origin $CIRCLE_BRANCH
            fi
  deploy-ci-job:
    <<: *defaults

    steps:
      - run:
          name: 'create build folder'
          command: 'mkdir build'
      - attach_workspace:
          at: ~/repo/build
      - run:
          name: Deploy Master to openode CI
          command: |
            cd build
            node_modules/.bin/openode deploy -t $OPENODE_TOKEN -s $OPENODE_SITE_CI
  deploy-prod-job:
    <<: *defaults

    steps:
      - run:
          name: 'create build folder'
          command: 'mkdir build'
      - attach_workspace:
          at: ~/repo/build
      - run:
          name: Deploy Master to openode CI
          command: |
            cd build
            node_modules/.bin/openode deploy -t $OPENODE_TOKEN -s $OPENODE_SITE

workflows:
  version: 2

  commit:
    jobs:
      - build-job
      - test-job:
          requires:
            - build-job
      - increment-build-job:
          requires:
            - test-job

  nightly_build:
    triggers:
      - schedule:
          cron: "0 0 * * *"
          filters:
            branches:
              only:
                - master
    jobs:
      - build-job
      - test-job:
          requires: 
            - build-job
      - increment-build-job:
          requires:
            - test-job
      - deploy-ci-job:
          requires: 
            - test-job
          filters:
            branches:
              only: 
                - master
  
  deploy:
    jobs:      
      - hold:
          type: approval
      - build-job:
          requires:
                - hold
      - test-job:
          requires:
            - build-job
      - deploy-prod-job:
          requires: 
            - test-job          
          filters:
            branches:
              only: 
                - master
  